### ISSUE TITLE
Complie error

### ISSUE THREAD

**Issue by Joechann0831** [V-Sense/LFBM5D#1]
Hi all, thanks for the code sharing. When I compile the code using cmake and make following the instructions of README, an error occurs:
/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/src/utilities_LF.cpp: In function ‘int get_params(int, char**, char**, char**, char**, bool&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, float&, float&, char**, char**, char**, char**, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, bool&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, bool&, unsigned int&, unsigned int&, char**)’:
/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/src/utilities_LF.cpp:1182:59: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     if(strcmp(*sub_img_name, "none" ) == 0) *sub_img_name = "";
                                                           ^
/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/src/utilities_LF.cpp:1184:41: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     if(strcmp(*sep, "none" ) == 0) *sep = "";
                                         ^
/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/src/utilities_LF.cpp: In function ‘int get_params_BM3D(int, char**, char**, char**, char**, bool&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, float&, float&, char**, char**, char**, char**, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, bool&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, unsigned int&, bool&, unsigned int&, unsigned int&, char**)’:
/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/src/utilities_LF.cpp:1390:59: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     if(strcmp(*sub_img_name, "none" ) == 0) *sub_img_name = "";
                                                           ^
/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/src/utilities_LF.cpp:1392:41: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     if(strcmp(*sep, "none" ) == 0) *sep = "";
                                         ^
[100%] Linking CXX executable ../../bin/LFBM5DSR
cd /media/joechan/Yun/Zhen/LFZSSR/LFBM5D/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/LFBM5DSR.dir/link.txt --verbose=1
/usr/bin/c++    -fopenmp -O3 -DNDEBUG    CMakeFiles/LFBM5DSR.dir/main.cpp.o CMakeFiles/LFBM5DSR.dir/bm3d.cpp.o CMakeFiles/LFBM5DSR.dir/bm5d.cpp.o CMakeFiles/LFBM5DSR.dir/bm5d_core_processing.cpp.o CMakeFiles/LFBM5DSR.dir/io_png.c.o CMakeFiles/LFBM5DSR.dir/lib_transforms.cpp.o CMakeFiles/LFBM5DSR.dir/mt19937ar.c.o CMakeFiles/LFBM5DSR.dir/utilities.cpp.o CMakeFiles/LFBM5DSR.dir/utilities_LF.cpp.o  -o ../../bin/LFBM5DSR -rdynamic -lfftw3f -lpng /home/joechan/anaconda3/lib/libz.so -Wl,-rpath,/home/joechan/anaconda3/lib 
CMakeFiles/LFBM5DSR.dir/io_png.c.o: In function `write_png_raw.constprop.1':
io_png.c:(.text+0x125): undefined reference to `png_set_longjmp_fn'
CMakeFiles/LFBM5DSR.dir/io_png.c.o: In function `write_png_raw.constprop.0':
io_png.c:(.text+0x7d3): undefined reference to `png_set_longjmp_fn'
CMakeFiles/LFBM5DSR.dir/io_png.c.o: In function `read_png_raw.constprop.2':
io_png.c:(.text+0xe0d): undefined reference to `png_set_longjmp_fn'
CMakeFiles/LFBM5DSR.dir/io_png.c.o: In function `read_png_raw.constprop.3':
io_png.c:(.text+0x111d): undefined reference to `png_set_longjmp_fn'
collect2: error: ld returned 1 exit status
src/CMakeFiles/LFBM5DSR.dir/build.make:306: recipe for target '../bin/LFBM5DSR' failed
make[2]: *** [../bin/LFBM5DSR] Error 1
make[2]: Leaving directory '/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/build'
CMakeFiles/Makefile2:88: recipe for target 'src/CMakeFiles/LFBM5DSR.dir/all' failed
make[1]: *** [src/CMakeFiles/LFBM5DSR.dir/all] Error 2
make[1]: Leaving directory '/media/joechan/Yun/Zhen/LFZSSR/LFBM5D/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

The compilation environment: Ubuntu 16.04, gcc/g++ version 5.5.0
Does anyone know how to solve it?

**Comment by malain35** [comment]
Hi,

this issue seems to be about linking libpng, this code was tested with libpng version 1.6.35, maybe installing this version could help.

Best,
Martin
