### ISSUE TITLE
How to process light fields with only Y channel?

### ISSUE THREAD

**Issue by Joechann0831** [V-Sense/LFBM5D#2]
Hi all, thanks for the code sharing. Recently I want to super-resolve a light field image with only Y channel, but when I input it to your LFBM5D code, the process dumped and an error occurs that "LFBM5DSR.exe has terminated" and then "Error when running LFBM5DSR at iteration 1" occurs in MATLAB. Do you know how to solve it? How can I run LFBM5D code with only Y channel?

**Comment by malain35** [comment]
Hi,

thanks for reporting this issue, the latest commit should have fixed it.

Best,
Martin
